Repository ROpdebee/mb-userscripts, pull requests merged in 2022-10, with the labels that each got.

#574 fix(caa-edits): Exclude inline entity creation dialogs
  mb_supercharged_caa_edits.user.js
Labels: bug, mb_supercharged_caa_edits

#581 fix(ecau): handle relative URLs in og:image providers
  src/mb_enhanced_cover_art_uploads/providers/base.ts
Labels: bug, mb_enhanced_cover_art_uploads

#588 ci: use environment files instead of deprecated ::set-output
  .github/actions/setup/action.yml
  build/deploy.ts
Labels: ci

#592 ci: fix deployment reporting
  build/deploy.ts
Labels: ci

#602 ci(deploy): fetch full repository history
  .github/workflows/deploy-preview.yml
  .github/workflows/deploy.yml
  .github/workflows/renovate-check.yml
Labels: ci

#603 ci(deploy): fix wrong param name to actions/checkout
  .github/workflows/deploy-preview.yml
  .github/workflows/deploy.yml
  .github/workflows/renovate-check.yml
Labels: ci

#606 ci: put npm cache on a monthly diet
  .github/actions/setup/action.yml
Labels: ci
